name: ultimate_salon_owner_flutter
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.13
  skeletons: ^0.0.3
  get: ^4.6.5
  image_picker: ^0.8.5+3
  syncfusion_flutter_calendar: ^20.1.57
  jiffy: ^5.0.0
  flutter_html: ^3.0.0-alpha.5
  connectivity_plus: ^2.3.5
  google_nav_bar: ^5.0.6
  syncfusion_flutter_charts: ^20.2.50
  flutter_otp_text_field: ^1.1.1
  webview_flutter: ^3.0.4
  country_code_picker: ^2.0.2
  url_launcher: ^6.1.5
  country_picker: ^2.0.16
  firebase_messaging: ^13.0.4
  firebase_core: ^1.24.0
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: semibold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
